spring:
  application:
    name: easy-retry-mybatis-demo

  easyretry:
    mybatis:
      enabled: true
      max-retry-times: 3

server:
  port: 8080

# MySQL 连接信息（请替换下面的 host/db/user/password）
easy:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.alibaba.easyretry: debug